"""Submarine command package. Re-exports ALL command classes for ST plugin loading."""
from .session_cmds import (  # noqa: F401
    SubmarineStartCommand,
    CodexStartCommand,
    DeepSeekStartCommand,
    PiStartCommand,
    GrokStartCommand,
    KimiStartCommand,
    SubmarineQueryCommand,
    SubmarineRestartCommand,
    SubmarineRestartNewCommand,
    SubmarineCopySessionIdCommand,
    SubmarineQueuePromptCommand,
    SubmarineInterruptCommand,
    SubmarineCloseSessionCommand,
    SubmarineRenameCommand,
    SubmarineToggleCommand,
    SubmarineStopCommand,
    SubmarineTearOffSessionCommand,
    SubmarineDockSessionCommand,
    SubmarineHideSessionCommand,
    SubmarineSleepSessionCommand,
    SubmarineWakeSessionCommand,
    SubmarineToggleAutoSleepCommand,
    SubmarineResumeCommand,
    SubmarineSwitchCommand,
    SubmarineForkCommand,
    SubmarineForkFromCommand,
    SubmarineSessionListCommand,
    SubmarineSessionListRefreshCommand,
    SubmarineSessionListOpenCommand,
)
from .provider_cmds import (  # noqa: F401
    SubmarineManageProvidersCommand,
    SubmarineStartCustomProviderCommand,
    SubmarineGenerateProviderModelsCommand,
    SubmarineChangeProviderCommand,
    SubmarineSelectEffortCommand,
    SubmarineSelectModelCommand,
    SubmarineSetDefaultModelCommand,
    SubmarineSetDefaultProviderCommand,
    SubmarineRefreshModelsCommand,
)
from .context_cmds import (  # noqa: F401
    SubmarineQuerySelectionCommand,
    SubmarineQueryFileCommand,
    SubmarineAddFileCommand,
    SubmarineAddSelectionCommand,
    SubmarineAddOpenFilesCommand,
    SubmarineAddFolderCommand,
    SubmarineClearContextCommand,
)
from .ui_cmds import (  # noqa: F401
    SubmarineClearCommand,
    SubmarineClearKeepLastCommand,
    SubmarineCopyCommand,
    SubmarineUsageCommand,
    SubmarineSearchSessionsCommand,
    SubmarineViewHistoryCommand,
    SubmarineResetInputCommand,
    SubmarineAddMcpCommand,
    SubmarineTogglePermissionModeCommand,
    SubmarineDevtoolsSnapshotCommand,
    SubmarineDevtoolsSessionsCommand,
    SubmarineDevtoolsComposerCommand,
    SubmarineDevtoolsLogCommand,
    SubmarineDevtoolsReloadCommand,
)
from .text_cmds import (  # noqa: F401
    SubmarineToggleSubmitModeCommand,
    SubmarineSendNowCommand,
    SubmarineSubmitInputCommand,
    SubmarineGoalStatusCommand,
    SubmarineGoalPauseCommand,
    SubmarineGoalResumeCommand,
    SubmarineGoalClearCommand,
    SubmarineInsertCommand,
    SubmarineToggleTasksFoldCommand,
    SubmarineReplaceCommand,
    SubmarineReplaceContentCommand,
    SubmarineClearAllCommand,
    SubmarineUndoClearCommand,
    SubmarineInsertNewlineCommand,
    NoopCommand,
    SubmarineSelectDraftCommand,
    SubmarineSelectHistoryCommand,
    SubmarinePermissionAllowCommand,
    SubmarinePermissionDenyCommand,
    SubmarineUndoMessageCommand,
    SubmarineViewPlanCommand,
    SubmarinePermissionAllowSessionCommand,
    SubmarinePermissionAllowAllCommand,
    SubmarineQuestionKeyCommand,
    SubmarineQuickPromptCommand,
    SubmarineManageAutoAllowedToolsCommand,
    SubmarinePasteImageCommand,
    SubmarineOpenLinkCommand,
    SubmarineRetainCommand,
    SubmarineProjectRetainCommand,
)

# Quick Agent host (defined in features/)
from features.quick import (  # noqa: F401
    SubmarineQuickAgentCommand,
    SubmarineQuickAgentConfigCommand,
    SubmarineQuickAgentStopCommand,
    SubmarineQuickAgentNewSlotCommand,
)

# Session-list extras (defined in ui/)
from ui.session_list import (  # noqa: F401
    SubmarineSessionJsonlCommand,
    SubmarineSessionListSetTextCommand,
    SubmarineSessionListCloseCommand,
    SubmarineSessionListRenameCommand,
    SubmarineSessionListForkCommand,
    SubmarineSessionListJsonlCommand,
    SubmarineSessionListStarCommand,
    SubmarineSessionListRevealCommand,
    SubmarineSessionListTearOffCommand,
)
